languageCode = "tr"
languageName = "Turkish"
weight = 1
title = "NKÜ Siber Güvenlik Topluluğu"

[params]
  displayName = "Turkish"
  isoCode = "tr"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/cmf-siber-guvenlik-logo.png"
  description = "NKÜ Siber Güvenlik Topluluğu İnternet Sitesi"

[author]
  name = "NKÜ Siber Güvenlik Topluluğu"
  email = "cmfsiber@gmail.com"
  image = "img/cmf-siber-guvenlik-logo.png"
  headline = "Kampüste dijital dönüşüm. Sen de bize katıl!"
  bio = "Kampüste dijital dönüşüm. Sen de bize katıl!"
  links = [
    { instagram = "https://instagram.com/cmfsiber" },
    { github = "https://github.com/cmfsiber" },
  ]
